version: '3.1'

services:
  mysql-v5: #Base de datos de Agencia
    image: mysql:5.5 # Imagen no oficial de MySQL 5.5
    container_name: sgbdr-mysql-v5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password #Definimos password porque sino nos genera uno automatico y no sabremos cual es
      MYSQL_DATABASE: agency
    ports:
      - "3306:3306"
    volumes:
      - mysql_v5_data:/var/lib/mysql

  mysql-v5-7: #Base de datos de Hotel
    image: mysql:5.7 # Imagen oficial de MySQL 5.7
    container_name: sgbdr-mysql-v5-7
    environment:
      MYSQL_DATABASE: hotel
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_v5_7_data:/var/lib/mysql

  mysql-v8: #Base de datos de Aerolinea
    image: mysql/mysql-server:8.0 # Imagen MySQL 8.0 con más soporte
    container_name: sgbdr-mysql-v8
    environment:
      MYSQL_DATABASE: airline
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_v8_data:/var/lib/mysql


volumes:
  mysql_v5_data:
  mysql_v5_7_data:
  mysql_v8_data: