
package ucm.tfg.agency.soapclient.airlineflight;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "AgencyAirlineFlightWS", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:9001/agencyMTA/AgencyAirlineFlightWS?wsdl")
public class AgencyAirlineFlightWS_Service
    extends Service
{

    private final static URL AGENCYAIRLINEFLIGHTWS_WSDL_LOCATION;
    private final static WebServiceException AGENCYAIRLINEFLIGHTWS_EXCEPTION;
    private final static QName AGENCYAIRLINEFLIGHTWS_QNAME = new QName("http://soap/", "AgencyAirlineFlightWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9001/agencyMTA/AgencyAirlineFlightWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGENCYAIRLINEFLIGHTWS_WSDL_LOCATION = url;
        AGENCYAIRLINEFLIGHTWS_EXCEPTION = e;
    }

    public AgencyAirlineFlightWS_Service() {
        super(__getWsdlLocation(), AGENCYAIRLINEFLIGHTWS_QNAME);
    }

    public AgencyAirlineFlightWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGENCYAIRLINEFLIGHTWS_QNAME, features);
    }

    public AgencyAirlineFlightWS_Service(URL wsdlLocation) {
        super(wsdlLocation, AGENCYAIRLINEFLIGHTWS_QNAME);
    }

    public AgencyAirlineFlightWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGENCYAIRLINEFLIGHTWS_QNAME, features);
    }

    public AgencyAirlineFlightWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgencyAirlineFlightWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgencyAirlineFlightWS
     */
    @WebEndpoint(name = "AgencyAirlineFlightWSPort")
    public AgencyAirlineFlightWS getAgencyAirlineFlightWSPort() {
        return super.getPort(new QName("http://soap/", "AgencyAirlineFlightWSPort"), AgencyAirlineFlightWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgencyAirlineFlightWS
     */
    @WebEndpoint(name = "AgencyAirlineFlightWSPort")
    public AgencyAirlineFlightWS getAgencyAirlineFlightWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "AgencyAirlineFlightWSPort"), AgencyAirlineFlightWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGENCYAIRLINEFLIGHTWS_EXCEPTION!= null) {
            throw AGENCYAIRLINEFLIGHTWS_EXCEPTION;
        }
        return AGENCYAIRLINEFLIGHTWS_WSDL_LOCATION;
    }

}
