
package ucm.tfg.agency.soapclient.airlinereservation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "AgencyAirlineReservationWS", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:9001/agencyMTA/AgencyAirlineReservationWS?wsdl")
public class AgencyAirlineReservationWS_Service
    extends Service
{

    private final static URL AGENCYAIRLINERESERVATIONWS_WSDL_LOCATION;
    private final static WebServiceException AGENCYAIRLINERESERVATIONWS_EXCEPTION;
    private final static QName AGENCYAIRLINERESERVATIONWS_QNAME = new QName("http://soap/", "AgencyAirlineReservationWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9001/agencyMTA/AgencyAirlineReservationWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGENCYAIRLINERESERVATIONWS_WSDL_LOCATION = url;
        AGENCYAIRLINERESERVATIONWS_EXCEPTION = e;
    }

    public AgencyAirlineReservationWS_Service() {
        super(__getWsdlLocation(), AGENCYAIRLINERESERVATIONWS_QNAME);
    }

    public AgencyAirlineReservationWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGENCYAIRLINERESERVATIONWS_QNAME, features);
    }

    public AgencyAirlineReservationWS_Service(URL wsdlLocation) {
        super(wsdlLocation, AGENCYAIRLINERESERVATIONWS_QNAME);
    }

    public AgencyAirlineReservationWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGENCYAIRLINERESERVATIONWS_QNAME, features);
    }

    public AgencyAirlineReservationWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgencyAirlineReservationWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgencyAirlineReservationWS
     */
    @WebEndpoint(name = "AgencyAirlineReservationWSPort")
    public AgencyAirlineReservationWS getAgencyAirlineReservationWSPort() {
        return super.getPort(new QName("http://soap/", "AgencyAirlineReservationWSPort"), AgencyAirlineReservationWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgencyAirlineReservationWS
     */
    @WebEndpoint(name = "AgencyAirlineReservationWSPort")
    public AgencyAirlineReservationWS getAgencyAirlineReservationWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "AgencyAirlineReservationWSPort"), AgencyAirlineReservationWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGENCYAIRLINERESERVATIONWS_EXCEPTION!= null) {
            throw AGENCYAIRLINERESERVATIONWS_EXCEPTION;
        }
        return AGENCYAIRLINERESERVATIONWS_WSDL_LOCATION;
    }

}
