
package ucm.tfg.agency.soapclient.airlinereservation;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AgencyAirlineReservationWS", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AgencyAirlineReservationWS {


    /**
     * 
     * @param idReservationAirline
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delFlightReservation", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.airlinereservation.DelFlightReservation")
    @ResponseWrapper(localName = "delFlightReservationResponse", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.airlinereservation.DelFlightReservationResponse")
    @Action(input = "http://soap/AgencyAirlineReservationWS/delFlightReservationRequest", output = "http://soap/AgencyAirlineReservationWS/delFlightReservationResponse")
    public double delFlightReservation(
        @WebParam(name = "idReservationAirline", targetNamespace = "")
        long idReservationAirline);

    /**
     * 
     * @param reservation
     * @return
     *     returns ucm.tfg.agency.soapclient.airlinereservation.AgencyReservationSuccessDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeFlightReservation", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.airlinereservation.MakeFlightReservation")
    @ResponseWrapper(localName = "makeFlightReservationResponse", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.airlinereservation.MakeFlightReservationResponse")
    @Action(input = "http://soap/AgencyAirlineReservationWS/makeFlightReservationRequest", output = "http://soap/AgencyAirlineReservationWS/makeFlightReservationResponse")
    public AgencyReservationSuccessDTO makeFlightReservation(
        @WebParam(name = "reservation", targetNamespace = "")
        MakeFlightReservationSOAP reservation);

    /**
     * 
     * @param reservation
     * @return
     *     returns ucm.tfg.agency.soapclient.airlinereservation.UpdateReservationDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modFlightReservation", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.airlinereservation.ModFlightReservation")
    @ResponseWrapper(localName = "modFlightReservationResponse", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.airlinereservation.ModFlightReservationResponse")
    @Action(input = "http://soap/AgencyAirlineReservationWS/modFlightReservationRequest", output = "http://soap/AgencyAirlineReservationWS/modFlightReservationResponse")
    public UpdateReservationDTO modFlightReservation(
        @WebParam(name = "reservation", targetNamespace = "")
        ModifyFlightReservationRequestionSOAP reservation);

}
