
package ucm.tfg.agency.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BookingsPort", targetNamespace = "http://ucm.tfg/hotelMTA")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookingsPort {


    /**
     * 
     * @param getBookingRequest
     * @return
     *     returns ucm.tfg.agency.soap.GetBookingResponse
     */
    @WebMethod
    @WebResult(name = "getBookingResponse", targetNamespace = "http://ucm.tfg/hotelMTA", partName = "getBookingResponse")
    public GetBookingResponse getBooking(
        @WebParam(name = "getBookingRequest", targetNamespace = "http://ucm.tfg/hotelMTA", partName = "getBookingRequest")
        GetBookingRequest getBookingRequest);

}
