
package ucm.tfg.agency.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BookingsPortService", targetNamespace = "http://ucm.tfg/hotelMTA", wsdlLocation = "http://localhost:8080/hotelMTA/ws/bookings.wsdl")
public class BookingsPortService
    extends Service
{

    private final static URL BOOKINGSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKINGSPORTSERVICE_EXCEPTION;
    private final static QName BOOKINGSPORTSERVICE_QNAME = new QName("http://ucm.tfg/hotelMTA", "BookingsPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/hotelMTA/ws/bookings.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKINGSPORTSERVICE_WSDL_LOCATION = url;
        BOOKINGSPORTSERVICE_EXCEPTION = e;
    }

    public BookingsPortService() {
        super(__getWsdlLocation(), BOOKINGSPORTSERVICE_QNAME);
    }

    public BookingsPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKINGSPORTSERVICE_QNAME, features);
    }

    public BookingsPortService(URL wsdlLocation) {
        super(wsdlLocation, BOOKINGSPORTSERVICE_QNAME);
    }

    public BookingsPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKINGSPORTSERVICE_QNAME, features);
    }

    public BookingsPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookingsPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookingsPort
     */
    @WebEndpoint(name = "BookingsPortSoap11")
    public BookingsPort getBookingsPortSoap11() {
        return super.getPort(new QName("http://ucm.tfg/hotelMTA", "BookingsPortSoap11"), BookingsPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookingsPort
     */
    @WebEndpoint(name = "BookingsPortSoap11")
    public BookingsPort getBookingsPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://ucm.tfg/hotelMTA", "BookingsPortSoap11"), BookingsPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKINGSPORTSERVICE_EXCEPTION!= null) {
            throw BOOKINGSPORTSERVICE_EXCEPTION;
        }
        return BOOKINGSPORTSERVICE_WSDL_LOCATION;
    }

}
