
package ucm.tfg.agency.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CustomersPortService", targetNamespace = "http://ucm.tfg/hotelMTA", wsdlLocation = "http://localhost:8080/hotelMTA/ws/customers.wsdl")
public class CustomersPortService
    extends Service
{

    private final static URL CUSTOMERSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERSPORTSERVICE_EXCEPTION;
    private final static QName CUSTOMERSPORTSERVICE_QNAME = new QName("http://ucm.tfg/hotelMTA", "CustomersPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/hotelMTA/ws/customers.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERSPORTSERVICE_WSDL_LOCATION = url;
        CUSTOMERSPORTSERVICE_EXCEPTION = e;
    }

    public CustomersPortService() {
        super(__getWsdlLocation(), CUSTOMERSPORTSERVICE_QNAME);
    }

    public CustomersPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERSPORTSERVICE_QNAME, features);
    }

    public CustomersPortService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERSPORTSERVICE_QNAME);
    }

    public CustomersPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERSPORTSERVICE_QNAME, features);
    }

    public CustomersPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomersPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomersPort
     */
    @WebEndpoint(name = "CustomersPortSoap11")
    public CustomersPort getCustomersPortSoap11() {
        return super.getPort(new QName("http://ucm.tfg/hotelMTA", "CustomersPortSoap11"), CustomersPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomersPort
     */
    @WebEndpoint(name = "CustomersPortSoap11")
    public CustomersPort getCustomersPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://ucm.tfg/hotelMTA", "CustomersPortSoap11"), CustomersPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERSPORTSERVICE_EXCEPTION!= null) {
            throw CUSTOMERSPORTSERVICE_EXCEPTION;
        }
        return CUSTOMERSPORTSERVICE_WSDL_LOCATION;
    }

}
