
package ucm.tfg.agency.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CustomersPort", targetNamespace = "http://ucm.tfg/hotelMTA")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomersPort {


    /**
     * 
     * @param getCustomerRequest
     * @return
     *     returns ucm.tfg.agency.soap.GetCustomerResponse
     */
    @WebMethod
    @WebResult(name = "getCustomerResponse", targetNamespace = "http://ucm.tfg/hotelMTA", partName = "getCustomerResponse")
    public GetCustomerResponse getCustomer(
        @WebParam(name = "getCustomerRequest", targetNamespace = "http://ucm.tfg/hotelMTA", partName = "getCustomerRequest")
        GetCustomerRequest getCustomerRequest);

}
