
package ucm.tfg.agency.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "RoomsPortService", targetNamespace = "http://ucm.tfg/hotelMTA", wsdlLocation = "http://localhost:8080/hotelMTA/ws/rooms.wsdl")
public class RoomsPortService
    extends Service
{

    private final static URL ROOMSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROOMSPORTSERVICE_EXCEPTION;
    private final static QName ROOMSPORTSERVICE_QNAME = new QName("http://ucm.tfg/hotelMTA", "RoomsPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/hotelMTA/ws/rooms.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROOMSPORTSERVICE_WSDL_LOCATION = url;
        ROOMSPORTSERVICE_EXCEPTION = e;
    }

    public RoomsPortService() {
        super(__getWsdlLocation(), ROOMSPORTSERVICE_QNAME);
    }

    public RoomsPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROOMSPORTSERVICE_QNAME, features);
    }

    public RoomsPortService(URL wsdlLocation) {
        super(wsdlLocation, ROOMSPORTSERVICE_QNAME);
    }

    public RoomsPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROOMSPORTSERVICE_QNAME, features);
    }

    public RoomsPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoomsPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RoomsPort
     */
    @WebEndpoint(name = "RoomsPortSoap11")
    public RoomsPort getRoomsPortSoap11() {
        return super.getPort(new QName("http://ucm.tfg/hotelMTA", "RoomsPortSoap11"), RoomsPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RoomsPort
     */
    @WebEndpoint(name = "RoomsPortSoap11")
    public RoomsPort getRoomsPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://ucm.tfg/hotelMTA", "RoomsPortSoap11"), RoomsPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROOMSPORTSERVICE_EXCEPTION!= null) {
            throw ROOMSPORTSERVICE_EXCEPTION;
        }
        return ROOMSPORTSERVICE_WSDL_LOCATION;
    }

}
