
package soapclient.airline.reservation;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReservationWS", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReservationWS {


    /**
     * 
     * @param request
     * @return
     *     returns soapclient.airline.reservation.SoapResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeReservation", targetNamespace = "http://soap/", className = "soapclient.airline.reservation.MakeReservation")
    @ResponseWrapper(localName = "makeReservationResponse", targetNamespace = "http://soap/", className = "soapclient.airline.reservation.MakeReservationResponse")
    @Action(input = "http://soap/ReservationWS/makeReservationRequest", output = "http://soap/ReservationWS/makeReservationResponse")
    public SoapResponse makeReservation(
        @WebParam(name = "request", targetNamespace = "")
        MakeReservationRequestSOAP request);

    /**
     * 
     * @param idFlight
     * @param idFlightInstance
     * @return
     *     returns soapclient.airline.reservation.SoapResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelReservation", targetNamespace = "http://soap/", className = "soapclient.airline.reservation.CancelReservation")
    @ResponseWrapper(localName = "cancelReservationResponse", targetNamespace = "http://soap/", className = "soapclient.airline.reservation.CancelReservationResponse")
    @Action(input = "http://soap/ReservationWS/cancelReservationRequest", output = "http://soap/ReservationWS/cancelReservationResponse")
    public SoapResponse cancelReservation(
        @WebParam(name = "idFlight", targetNamespace = "")
        long idFlight,
        @WebParam(name = "idFlightInstance", targetNamespace = "")
        long idFlightInstance);

    /**
     * 
     * @param idReservation
     * @return
     *     returns soapclient.airline.reservation.SoapResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchReservation", targetNamespace = "http://soap/", className = "soapclient.airline.reservation.SearchReservation")
    @ResponseWrapper(localName = "searchReservationResponse", targetNamespace = "http://soap/", className = "soapclient.airline.reservation.SearchReservationResponse")
    @Action(input = "http://soap/ReservationWS/searchReservationRequest", output = "http://soap/ReservationWS/searchReservationResponse")
    public SoapResponse searchReservation(
        @WebParam(name = "idReservation", targetNamespace = "")
        long idReservation);

    /**
     * 
     * @param request
     * @return
     *     returns soapclient.airline.reservation.SoapResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyReservation", targetNamespace = "http://soap/", className = "soapclient.airline.reservation.ModifyReservation")
    @ResponseWrapper(localName = "modifyReservationResponse", targetNamespace = "http://soap/", className = "soapclient.airline.reservation.ModifyReservationResponse")
    @Action(input = "http://soap/ReservationWS/modifyReservationRequest", output = "http://soap/ReservationWS/modifyReservationResponse")
    public SoapResponse modifyReservation(
        @WebParam(name = "request", targetNamespace = "")
        ModifyReservationRequestSOAP request);

}
