
package ucm.tfg.agency.soapclient.hotelbooking;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "AgencyHotelBookingWS", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:9001/agencyMTA/AgencyHotelBookingWS?wsdl")
public class AgencyHotelBookingWS_Service
    extends Service
{

    private final static URL AGENCYHOTELBOOKINGWS_WSDL_LOCATION;
    private final static WebServiceException AGENCYHOTELBOOKINGWS_EXCEPTION;
    private final static QName AGENCYHOTELBOOKINGWS_QNAME = new QName("http://soap/", "AgencyHotelBookingWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9001/agencyMTA/AgencyHotelBookingWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGENCYHOTELBOOKINGWS_WSDL_LOCATION = url;
        AGENCYHOTELBOOKINGWS_EXCEPTION = e;
    }

    public AgencyHotelBookingWS_Service() {
        super(__getWsdlLocation(), AGENCYHOTELBOOKINGWS_QNAME);
    }

    public AgencyHotelBookingWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGENCYHOTELBOOKINGWS_QNAME, features);
    }

    public AgencyHotelBookingWS_Service(URL wsdlLocation) {
        super(wsdlLocation, AGENCYHOTELBOOKINGWS_QNAME);
    }

    public AgencyHotelBookingWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGENCYHOTELBOOKINGWS_QNAME, features);
    }

    public AgencyHotelBookingWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgencyHotelBookingWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgencyHotelBookingWS
     */
    @WebEndpoint(name = "AgencyHotelBookingWSPort")
    public AgencyHotelBookingWS getAgencyHotelBookingWSPort() {
        return super.getPort(new QName("http://soap/", "AgencyHotelBookingWSPort"), AgencyHotelBookingWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgencyHotelBookingWS
     */
    @WebEndpoint(name = "AgencyHotelBookingWSPort")
    public AgencyHotelBookingWS getAgencyHotelBookingWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "AgencyHotelBookingWSPort"), AgencyHotelBookingWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGENCYHOTELBOOKINGWS_EXCEPTION!= null) {
            throw AGENCYHOTELBOOKINGWS_EXCEPTION;
        }
        return AGENCYHOTELBOOKINGWS_WSDL_LOCATION;
    }

}
