
package ucm.tfg.agency.soapclient.hotelbooking;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "AgencyHotelBookingWS", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AgencyHotelBookingWS {


    /**
     * 
     * @param bookingId
     * @return
     *     returns ucm.tfg.agency.soapclient.hotelbooking.BookingDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readHotelBooking", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.hotelbooking.ReadHotelBooking")
    @ResponseWrapper(localName = "readHotelBookingResponse", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.hotelbooking.ReadHotelBookingResponse")
    @Action(input = "http://soap/AgencyHotelBookingWS/readHotelBookingRequest", output = "http://soap/AgencyHotelBookingWS/readHotelBookingResponse")
    public BookingDTO readHotelBooking(
        @WebParam(name = "bookingId", targetNamespace = "")
        int bookingId);

    /**
     * 
     * @param booking
     * @param user
     * @param dni
     * @return
     *     returns ucm.tfg.agency.soapclient.hotelbooking.BookingDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeHotelBooking", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.hotelbooking.MakeHotelBooking")
    @ResponseWrapper(localName = "makeHotelBookingResponse", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.hotelbooking.MakeHotelBookingResponse")
    @Action(input = "http://soap/AgencyHotelBookingWS/makeHotelBookingRequest", output = "http://soap/AgencyHotelBookingWS/makeHotelBookingResponse")
    public BookingDTO makeHotelBooking(
        @WebParam(name = "booking", targetNamespace = "")
        MakeBookingReservationDTO booking,
        @WebParam(name = "user", targetNamespace = "")
        long user,
        @WebParam(name = "dni", targetNamespace = "")
        String dni);

    /**
     * 
     * @param bookingId
     * @param roomId
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelHotelBookingLine", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.hotelbooking.CancelHotelBookingLine")
    @ResponseWrapper(localName = "cancelHotelBookingLineResponse", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.hotelbooking.CancelHotelBookingLineResponse")
    @Action(input = "http://soap/AgencyHotelBookingWS/cancelHotelBookingLineRequest", output = "http://soap/AgencyHotelBookingWS/cancelHotelBookingLineResponse")
    public double cancelHotelBookingLine(
        @WebParam(name = "bookingId", targetNamespace = "")
        long bookingId,
        @WebParam(name = "roomId", targetNamespace = "")
        long roomId);

    /**
     * 
     * @param booking
     * @return
     *     returns ucm.tfg.agency.soapclient.hotelbooking.BookingDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyHotelBooking", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.hotelbooking.ModifyHotelBooking")
    @ResponseWrapper(localName = "modifyHotelBookingResponse", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.hotelbooking.ModifyHotelBookingResponse")
    @Action(input = "http://soap/AgencyHotelBookingWS/modifyHotelBookingRequest", output = "http://soap/AgencyHotelBookingWS/modifyHotelBookingResponse")
    public BookingDTO modifyHotelBooking(
        @WebParam(name = "booking", targetNamespace = "")
        ModifyBookingReservationDTO booking);

    /**
     * 
     * @param bookingId
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelHotelBooking", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.hotelbooking.CancelHotelBooking")
    @ResponseWrapper(localName = "cancelHotelBookingResponse", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.hotelbooking.CancelHotelBookingResponse")
    @Action(input = "http://soap/AgencyHotelBookingWS/cancelHotelBookingRequest", output = "http://soap/AgencyHotelBookingWS/cancelHotelBookingResponse")
    public double cancelHotelBooking(
        @WebParam(name = "bookingId", targetNamespace = "")
        long bookingId);

}
