
package ucm.tfg.agency.soapclient.hotelroom;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "AgencyHotelRoomWS", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:9001/agencyMTA/AgencyHotelRoomWS?wsdl")
public class AgencyHotelRoomWS_Service
    extends Service
{

    private final static URL AGENCYHOTELROOMWS_WSDL_LOCATION;
    private final static WebServiceException AGENCYHOTELROOMWS_EXCEPTION;
    private final static QName AGENCYHOTELROOMWS_QNAME = new QName("http://soap/", "AgencyHotelRoomWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9001/agencyMTA/AgencyHotelRoomWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGENCYHOTELROOMWS_WSDL_LOCATION = url;
        AGENCYHOTELROOMWS_EXCEPTION = e;
    }

    public AgencyHotelRoomWS_Service() {
        super(__getWsdlLocation(), AGENCYHOTELROOMWS_QNAME);
    }

    public AgencyHotelRoomWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGENCYHOTELROOMWS_QNAME, features);
    }

    public AgencyHotelRoomWS_Service(URL wsdlLocation) {
        super(wsdlLocation, AGENCYHOTELROOMWS_QNAME);
    }

    public AgencyHotelRoomWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGENCYHOTELROOMWS_QNAME, features);
    }

    public AgencyHotelRoomWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgencyHotelRoomWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgencyHotelRoomWS
     */
    @WebEndpoint(name = "AgencyHotelRoomWSPort")
    public AgencyHotelRoomWS getAgencyHotelRoomWSPort() {
        return super.getPort(new QName("http://soap/", "AgencyHotelRoomWSPort"), AgencyHotelRoomWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgencyHotelRoomWS
     */
    @WebEndpoint(name = "AgencyHotelRoomWSPort")
    public AgencyHotelRoomWS getAgencyHotelRoomWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "AgencyHotelRoomWSPort"), AgencyHotelRoomWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGENCYHOTELROOMWS_EXCEPTION!= null) {
            throw AGENCYHOTELROOMWS_EXCEPTION;
        }
        return AGENCYHOTELROOMWS_WSDL_LOCATION;
    }

}
