
package hotelmta;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelWSB", targetNamespace = "http://soap.hotelmta.tfg/", wsdlLocation = "http://localhost:8888/HotelWSB?wsdl")
public class HotelWSB_Service
    extends Service
{

    private final static URL HOTELWSB_WSDL_LOCATION;
    private final static WebServiceException HOTELWSB_EXCEPTION;
    private final static QName HOTELWSB_QNAME = new QName("http://soap.hotelmta.tfg/", "HotelWSB");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/HotelWSB?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELWSB_WSDL_LOCATION = url;
        HOTELWSB_EXCEPTION = e;
    }

    public HotelWSB_Service() {
        super(__getWsdlLocation(), HOTELWSB_QNAME);
    }

    public HotelWSB_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELWSB_QNAME, features);
    }

    public HotelWSB_Service(URL wsdlLocation) {
        super(wsdlLocation, HOTELWSB_QNAME);
    }

    public HotelWSB_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELWSB_QNAME, features);
    }

    public HotelWSB_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelWSB_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HotelWSB
     */
    @WebEndpoint(name = "HotelWSBPort")
    public HotelWSB getHotelWSBPort() {
        return super.getPort(new QName("http://soap.hotelmta.tfg/", "HotelWSBPort"), HotelWSB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelWSB
     */
    @WebEndpoint(name = "HotelWSBPort")
    public HotelWSB getHotelWSBPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.hotelmta.tfg/", "HotelWSBPort"), HotelWSB.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELWSB_EXCEPTION!= null) {
            throw HOTELWSB_EXCEPTION;
        }
        return HOTELWSB_WSDL_LOCATION;
    }

}
