
package hotelmta;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelWSB", targetNamespace = "http://soap.hotelmta.tfg/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelWSB {


    /**
     * 
     * @param arg1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchRoom", targetNamespace = "http://soap.hotelmta.tfg/", className = "hotelmta.SearchRoom")
    @ResponseWrapper(localName = "searchRoomResponse", targetNamespace = "http://soap.hotelmta.tfg/", className = "hotelmta.SearchRoomResponse")
    @Action(input = "http://soap.hotelmta.tfg/HotelWSB/searchRoomRequest", output = "http://soap.hotelmta.tfg/HotelWSB/searchRoomResponse")
    public Object searchRoom(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
