
package ucm.tfg.agency.soapclient.gatewayagency;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "GatewayAgencyWS", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:9001/agencyMTA/GatewayAgencyWS?wsdl")
public class GatewayAgencyWS_Service
    extends Service
{

    private final static URL GATEWAYAGENCYWS_WSDL_LOCATION;
    private final static WebServiceException GATEWAYAGENCYWS_EXCEPTION;
    private final static QName GATEWAYAGENCYWS_QNAME = new QName("http://soap/", "GatewayAgencyWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9001/agencyMTA/GatewayAgencyWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GATEWAYAGENCYWS_WSDL_LOCATION = url;
        GATEWAYAGENCYWS_EXCEPTION = e;
    }

    public GatewayAgencyWS_Service() {
        super(__getWsdlLocation(), GATEWAYAGENCYWS_QNAME);
    }

    public GatewayAgencyWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GATEWAYAGENCYWS_QNAME, features);
    }

    public GatewayAgencyWS_Service(URL wsdlLocation) {
        super(wsdlLocation, GATEWAYAGENCYWS_QNAME);
    }

    public GatewayAgencyWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GATEWAYAGENCYWS_QNAME, features);
    }

    public GatewayAgencyWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GatewayAgencyWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GatewayAgencyWS
     */
    @WebEndpoint(name = "GatewayAgencyWSPort")
    public GatewayAgencyWS getGatewayAgencyWSPort() {
        return super.getPort(new QName("http://soap/", "GatewayAgencyWSPort"), GatewayAgencyWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GatewayAgencyWS
     */
    @WebEndpoint(name = "GatewayAgencyWSPort")
    public GatewayAgencyWS getGatewayAgencyWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "GatewayAgencyWSPort"), GatewayAgencyWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GATEWAYAGENCYWS_EXCEPTION!= null) {
            throw GATEWAYAGENCYWS_EXCEPTION;
        }
        return GATEWAYAGENCYWS_WSDL_LOCATION;
    }

}
