
package ucm.tfg.agency.soapclient.gatewayagency;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "GatewayAgencyWS", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GatewayAgencyWS {


    /**
     * 
     * @param paramSearchTravel
     * @return
     *     returns ucm.tfg.agency.soapclient.gatewayagency.GetTravelSOAP
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchTravel", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.gatewayagency.SearchTravel")
    @ResponseWrapper(localName = "searchTravelResponse", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.gatewayagency.SearchTravelResponse")
    @Action(input = "http://soap/GatewayAgencyWS/searchTravelRequest", output = "http://soap/GatewayAgencyWS/searchTravelResponse")
    public GetTravelSOAP searchTravel(
        @WebParam(name = "paramSearchTravel", targetNamespace = "")
        long paramSearchTravel);

    /**
     * 
     * @param parmaSearchAirlineHotel
     * @return
     *     returns ucm.tfg.agency.soapclient.gatewayagency.SearchFlightHotelResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchFlightHotel", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.gatewayagency.SearchFlightHotel")
    @ResponseWrapper(localName = "searchFlightHotelResponse", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.gatewayagency.SearchFlightHotelResponse")
    @Action(input = "http://soap/GatewayAgencyWS/searchFlightHotelRequest", output = "http://soap/GatewayAgencyWS/searchFlightHotelResponse")
    public ucm.tfg.agency.soapclient.gatewayagency.SearchFlightHotelResponse.Return searchFlightHotel(
        @WebParam(name = "parmaSearchAirlineHotel", targetNamespace = "")
        SearchAirlineHotelRequestSOAP parmaSearchAirlineHotel);

    /**
     * 
     * @param flightReservationId
     * @param hotelBookingId
     * @return
     *     returns ucm.tfg.agency.soapclient.gatewayagency.HotelFlightReservationDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFlightHotelReservation", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.gatewayagency.GetFlightHotelReservation")
    @ResponseWrapper(localName = "getFlightHotelReservationResponse", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.gatewayagency.GetFlightHotelReservationResponse")
    @Action(input = "http://soap/GatewayAgencyWS/getFlightHotelReservationRequest", output = "http://soap/GatewayAgencyWS/getFlightHotelReservationResponse")
    public HotelFlightReservationDTO getFlightHotelReservation(
        @WebParam(name = "hotelBookingId", targetNamespace = "")
        long hotelBookingId,
        @WebParam(name = "flightReservationId", targetNamespace = "")
        long flightReservationId);

    /**
     * 
     * @param idUser
     * @return
     *     returns java.util.List<ucm.tfg.agency.soapclient.gatewayagency.GetTravelSOAP>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchTravelByIdUser", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.gatewayagency.SearchTravelByIdUser")
    @ResponseWrapper(localName = "searchTravelByIdUserResponse", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.gatewayagency.SearchTravelByIdUserResponse")
    @Action(input = "http://soap/GatewayAgencyWS/searchTravelByIdUserRequest", output = "http://soap/GatewayAgencyWS/searchTravelByIdUserResponse")
    public List<GetTravelSOAP> searchTravelByIdUser(
        @WebParam(name = "idUser", targetNamespace = "")
        long idUser);

    /**
     * 
     * @param booking
     * @param reservation
     * @return
     *     returns ucm.tfg.agency.soapclient.gatewayagency.AgencyReservationSuccessDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeFlightHotelReservation", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.gatewayagency.MakeFlightHotelReservation")
    @ResponseWrapper(localName = "makeFlightHotelReservationResponse", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.gatewayagency.MakeFlightHotelReservationResponse")
    @Action(input = "http://soap/GatewayAgencyWS/makeFlightHotelReservationRequest", output = "http://soap/GatewayAgencyWS/makeFlightHotelReservationResponse")
    public AgencyReservationSuccessDTO makeFlightHotelReservation(
        @WebParam(name = "booking", targetNamespace = "")
        MakeBookingReservationDTO booking,
        @WebParam(name = "reservation", targetNamespace = "")
        MakeFlightReservationSOAP reservation);

    /**
     * 
     * @param booking
     * @param reservation
     * @return
     *     returns ucm.tfg.agency.soapclient.gatewayagency.UpdateReservationDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modFlightHotelReservation", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.gatewayagency.ModFlightHotelReservation")
    @ResponseWrapper(localName = "modFlightHotelReservationResponse", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.gatewayagency.ModFlightHotelReservationResponse")
    @Action(input = "http://soap/GatewayAgencyWS/modFlightHotelReservationRequest", output = "http://soap/GatewayAgencyWS/modFlightHotelReservationResponse")
    public UpdateReservationDTO modFlightHotelReservation(
        @WebParam(name = "booking", targetNamespace = "")
        ModifyBookingReservationDTO booking,
        @WebParam(name = "reservation", targetNamespace = "")
        ModifyFlightReservationRequestionSOAP reservation);

    /**
     * 
     * @param flightReservationId
     * @param hotelBookingId
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delFlightHotelReservation", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.gatewayagency.DelFlightHotelReservation")
    @ResponseWrapper(localName = "delFlightHotelReservationResponse", targetNamespace = "http://soap/", className = "ucm.tfg.agency.soapclient.gatewayagency.DelFlightHotelReservationResponse")
    @Action(input = "http://soap/GatewayAgencyWS/delFlightHotelReservationRequest", output = "http://soap/GatewayAgencyWS/delFlightHotelReservationResponse")
    public double delFlightHotelReservation(
        @WebParam(name = "hotelBookingId", targetNamespace = "")
        long hotelBookingId,
        @WebParam(name = "flightReservationId", targetNamespace = "")
        long flightReservationId);

}
